### ISSUE TITLE
Display of periodical issue's title 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-presentation#111]
_Problem description:_
From several persons, criticism regarding the display of the title of periodical issues in result lists arose. The problem is the display of _[kein Titel]_ instead of the periodical's title [1]. 

In long result lists, this becaomes quite confusing. The RSS-Feed faced the similar problem, which was solved by Goobi.Presentation CE 1.1.b2 [2]. In the release notes, it seems as if the problem should be solvable in the presentation, too: 

> "- Für Bände ohne eigenen Titel kann nun wahlweise der Titel der übergeordneten Einheit in eckigen Klammern angezeigt werden. Das ist beispielsweise in den RSS-Feeds interessant, um dort "leere" Einträge zu vermeiden, kann aber auch im Metadaten-Plugin verwendet werden. Das Feature lässt sich über die Plugin-Konfiguration individuell ein- und ausschalten."

_Solution description:_
In the result lists, periodical issues should be labeled with the periodical's title, except when the issue has an own title. 

[1] 
![kein_titel](https://cloud.githubusercontent.com/assets/14835770/13820233/b2597d48-eb9c-11e5-8c0d-3bc52dd8229f.jpg) 

[2]
![mit_titel](https://cloud.githubusercontent.com/assets/14835770/13820431/9f389f40-eb9d-11e5-9813-4f7f81c2ca00.jpg)

**Comment by albig** [comment]
I think this is already fixed. The mentionend option was not activated in our digital collections.

![goobi-presentation-title_subentry](https://cloud.githubusercontent.com/assets/3354500/15120687/30fbf1ea-1617-11e6-9ff2-93263cfafc19.jpg)

**Comment by andre-hohmann** [comment]
Unfortunately, it is not fixed. 

The mentioned example [1] is about a **multivolume** and the metadata _main title_ in the firstchild-element is assigned manually. 

The example [2] from the problem description is about a **periodical**, which metadata _main title_ in the firstchild element **is not** assigned manually. 
It is the metadata _CurrentNo_ [3] which is assigned and which should be displayed.  

[1] Beitrag zur Reformations-Geschichte der Stadt Görlitz ([http://digital.slub-dresden.de/id445729600](http://digital.slub-dresden.de/id445729600)) 
[2] [http://digital.slub-dresden.de/kollektionen/150/](http://digital.slub-dresden.de/kollektionen/150/) 
[3] Other names: Bandzählung - ./mods:mods/mods:part/mods:detail/mods:number

**Comment by albig** [comment]
Thanks for clarifying.

**Comment by sebastian-meyer** [comment]
There is no difference between periodicals and multivolume works. @albig was right: the feature just wasn't activated in our instance of Kitodo.Presentation. I activated it and now your example shows the title of the superior work, too: http://digital.slub-dresden.de/kollektionen/150/
The part number is not shown, because it is currently not defined as a "listed" metadata field for the listview. But that's a matter of configuration, not a bug in Kitodo.Presentation.
